# Generated by Django 2.0 on 2019-12-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FindPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgname', models.CharField(default='Stella Dimora', max_length=100)),
                ('pgaddress', models.CharField(default='Stella Dimora,United Kingdom', max_length=100)),
                ('rentchoice', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='monthly', max_length=6)),
                ('roomchoice', models.CharField(choices=[('singleroom', 'Singleroom'), ('twosharedroom', 'Twosharedroom'), ('threesharedroom', 'Threesharedroom'), ('foursharedroom', 'Foursharedroom')], default='singleroom', max_length=6)),
                ('mealchoice', models.CharField(choices=[('onetime', 'Breakfast only'), ('twotimes', 'Breakfast & Dinner'), ('threetimes', 'Breakfast, Lunch & Dinner')], default='threetimes', max_length=6)),
                ('location', models.CharField(choices=[('uk', 'United Kingdom'), ('australia', 'Australia'), ('canada', 'Canada'), ('germany', 'Germany')], default='australia', max_length=6)),
                ('contactno', models.IntegerField()),
            ],
        ),
    ]
