# Generated by Django 2.0 on 2019-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGFinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findpg',
            name='contactno',
            field=models.CharField(default='null', max_length=12),
        ),
    ]
