# Generated by Django 2.0 on 2020-05-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0002_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='Goalscore',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
